config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]

    post :show, on: :member
  end

  resources :users, only: %i[show edit update]
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true,
                    length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # Задаем объект @event для тех действий, где он нужен
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[show edit update destroy]
  before_action :password_guard!, only: [:show]

  after_action :verify_authorized, only: %i[show edit update destroy]
  after_action :verify_policy_scoped, only: :index
  def index
    @events = policy_scope(Event)
  end

  def show
    authorize @event
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)
    authorize @event
    
    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private
  

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end

  def password_guard!
    # Если у события нет пин-кода, то охранять нечего
    return true if @event.pincode.blank?
    # Пин-код не нужен автору события
    return true if signed_in? && current_user == @event.user
  
    # Если нам передали код и он верный, сохраняем его в куки этого юзера
    # Так юзеру не нужно будет вводить пин-код каждый раз
    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end
  
    # Проверяем, верный ли в куках пин-код
    # Если нет — ругаемся и рендерим форму ввода пин-кода
    pincode = cookies.permanent["events_#{@event.id}_pincode"]
    unless @event.pincode_valid?(pincode)
      if params[:pincode].present?
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
      end
      render 'password_form'
    end
  end
end

app/views/events/_event.html.erb
<%# Паршиал для отображения инфы об отдельном событии %>
<div class="col-sm-6 col-md-4 mb-2">
  <div class="thumbnail image-for-bg">

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description text-center">
          <h3 class="text-wrap"><%= link_to event.title, event_path(event) %></h3>
          <h3 class="text-wrap"><small><%= l event.datetime, format: :short %></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%# Паршиал дляотображения формы создания нового события %>
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %><br/>
    <em>(Если хотите, чтобы доступ был только у избранных)</em>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions my-1">
    <%= f.submit 'Сохранить', class: 'btn btn-info' %>
    или <%= link_to 'Вернуться', :back, class: 'btn btn-info' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>
<% if current_user_can_edit?(@event) %>
  <div class="buffer-top">
    <%= link_to t('links.destroy_event_button'), event_path(@event), data: { confirm: t('links.destroy_event') },
                method: :delete, class: 'btn btn-danger my-2' %>
  </div>
<% end %>

app/views/events/index.html.erb
<h1 class="text-center">Добро пожаловать в Ситком про Канатчикову дачу!</h1>

<div class="buffer-both text-center my-5">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-info' %>
</div>

<div class="row buffer-bottom">
  <%# Рендерим сразу массив событий, каждый в паршиале 'events/event' %>
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1>Доступ только по пин-коду</h1>

<%= form_for('', method: 'post') do |f| %>
  <div class="form-group">
    <%= f.label :pincode, t('activerecord.attributes.event.pincode') %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit t('links.log_in'), class: 'btn btn-info'%>
  </div>
<% end %>

<%= link_to t('links.back'), root_path, class: 'btn btn-info my-2' %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%#= content_tag 'div', '', class: 'event-background image-for-bg' %>
      <%= content_tag 'div', '', class: 'event-background', style: "background-image: url(#{event_photo(@event)}" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-top">
              <%= link_to t('links.change'), edit_event_path(@event),
                          class: 'btn btn-info my-1' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="map"
     data-address="<%= @event.address %>"
     style="width: 100%; height: 250px"
     class="my-2"></div>

<div class="row">
  <div class="col-md-8">
    <div class="event-photo-form">
      <div class="event-photos-gallery border-bottom my-2">
        <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
      </div>

      <%= render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build } %>
    </div>
    <div class="event-comments buffer-top">
      <%= render partial: 'comments/form',
                 locals: { comment: @new_comment || @event.comments.build } %>

      <div class="buffer-both">
        <%= render partial: 'comments/comment',
                   collection: @event.comments.except(@new_comment), order: :desc %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="event-owner">
      <h4>Зовет:</h4>
      <p><%= render partial: 'users/user', object: @event.user %></p>
    </div>
    <div class="event-subscriptions">
      <h4>Пойдут:</h4>
      <% if @event.subscriptions.persisted.empty? %>
        <p>Пока никто не идёт :(</p>
      <% else %>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
                       collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      <% end %>
    </div>
    <% unless current_user == @event.user || @event.subscribers.include?(current_user) %>
        <div class="event-subscription-form">
          <h4>Я пойду!</h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
                subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
    <% end %>
  </div>
</div>