config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]

    post :show, on: :member
  end

  resources :users, only: %i[show edit update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user
  
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where 'id IS NOT NULL' }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: %i[create destroy]
  before_action :set_photo, only: [:destroy]

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user

    if @new_photo.save
      NotifyJob.perform_later(@new_photo)
      redirect_to @event, notice: I18n.t('controllers.photos.created')
    else
      render 'events/show', alert: I18n.t('controllers.photos.error')
    end
  end

  def destroy
    message = { notice: I18n.t('controllers.photos.destroyed') }

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = { alert: I18n.t('controllers.photos.error') }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end
end

app/views/photos/_form.html.erb
<%= form_for [@event, photo], html: { multipart: true } do |f| %>
  <%= render partial: 'partials/form_errors', locals: { model: photo } %>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit 'Загрузить', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div class="event-photo buffer-both">
  <% image_title = "#{t('photo.photo.added')} #{render partial: 'users/user', object: photo.user}" %>
  <% if current_user_can_edit?(photo) %>
    <% image_title += link_to fa_icon('trash'), event_photo_path(photo.event, photo),
                              method: :delete, data: { confirm: t('links.delete_photo') } %>
  <% end %>

  <% if photo.photo.thumb.url %>
    <%= link_to image_tag(photo.photo.thumb.url), photo.photo.url,
                data: {
                    lightbox: "event-photos",
                    title: image_title
                } %>
  <% end %>
</div>